### ISSUE TITLE
Créer un service todo

### ISSUE THREAD

**Issue by billykiwee** [yoann90/Todo#2]
### Description
Il est nécessaire de créer un fichier JavaScript dédié pour gérer les tâches du service todo. Ce fichier centralisera les fonctions CRUD (Create, Read, Update, Delete) pour une gestion efficace des tâches.

### À faire
- [x] Créer un fichier `todo.service.js`.
- [x] Implémenter la fonction **Create** pour ajouter de nouvelles tâches.
- [x] Implémenter la fonction **Read** pour afficher les tâches depuis le local storage.
- [x] Implémenter la fonction **Update** pour modifier les tâches (édition, marquage comme complétée).
- [x] Implémenter la fonction **Delete** pour supprimer des tâches.
- [x] Tester les fonctions CRUD pour vérifier leur bon fonctionnement.

### Résultat attendu
Un fichier `todo.service.js` fonctionnel, gérant toutes les opérations CRUD pour les tâches.

**Comment by auraalex21** [comment]
## modification JS
Compresser le plus possible pour éviter le trop-plein de ligne.

**Comment by Softexus** [comment]
Beaucoup chose à encore reprendre + un bug lors du clique sur l'icon trash

**Comment by billykiwee** [comment]
## Créer **UNIQUEMENT** un fichier `todo.service.js`
